<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    'Models\\' => array($baseDir . '/src/Models'),
    'Katzgrau\\KLogger\\' => array($vendorDir . '/katzgrau/klogger/src'),
    'Framework\\Helpers\\' => array($baseDir . '/src/Framework/Helpers'),
    'Framework\\' => array($baseDir . '/src/Framework'),
    'Controllers\\' => array($baseDir . '/src/Controllers'),
);
